### ISSUE TITLE
Nombre y logo

### ISSUE THREAD

**Issue by Nidev-lab** [ochay33/proyecto-Bar-Nadir#29]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Encontrar nombre y logo de la pagina.

## Resultado actual

• No se encuentra logo ni nombre de la misma.

## Captura

![image](https://github.com/ochay33/proyecto-Bar-Nadir/assets/53904695/8b919ae8-31f2-4444-8328-272cb5eaf079)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Nidev-lab** [comment]
Chicos buenas! Tendrían algún user admin que me pasen para poder continuar con la devolución del proyecto?

**Comment by ochay33** [comment]
User: ***@***.***
Contraseña: 123456

**Comment by ochay33** [comment]
Nombre y logo modificados.
