### ISSUE TITLE
Pedidos

### ISSUE THREAD

**Issue by Nidev-lab** [ochay33/proyecto-Bar-Nadir#30]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario.
3. Agregue uno pedidos al carrito.

## Resultado esperado

• Que la pedidos realizados mantengan la cantidad solicitada.

## Resultado actual

• Al realizar un pedido nuevo la cantidad solicitada en el pedido anterior se modifica por la cantidad del pedido nuevo.
Ejemplo: Pedí 2 empanadas y 6 tacos, pero en el carrito me figura que pedí 6 empanadas y 6 tacos. 

## Captura

![image](https://github.com/ochay33/proyecto-Bar-Nadir/assets/53904695/9e6f1048-53ac-446c-95f8-ed9b0f14e009)
![image](https://github.com/ochay33/proyecto-Bar-Nadir/assets/53904695/e49bf5da-311d-46cd-bb60-f25b70ff9f5a)
![image](https://github.com/ochay33/proyecto-Bar-Nadir/assets/53904695/6cbd752e-73f8-4391-8dc8-57a8ff4008fd)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by ochay33** [comment]
Problema resuelto.
