### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Nidev-lab** [ochay33/proyecto-Bar-Nadir#31]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Que al hacer click en el logo me redirija a la pagina de inicio.

## Resultado actual

• Al hacer click en el logo no redirecciona a ningún sitio.

## Captura

![image](https://github.com/ochay33/proyecto-Bar-Nadir/assets/53904695/d1b0ea8b-7c41-46fd-bdaa-8820c84ac861)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by ochay33** [comment]
Ya se modificó y resolvio.
