### ISSUE TITLE
Carrito

### ISSUE THREAD

**Issue by Nidev-lab** [ochay33/proyecto-Bar-Nadir#32]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario nuevo.

## Resultado esperado

• Al ingresar no tener nada en el carrito.

## Resultado actual

• Al ingresar con un usuario nuevo, en el carrito quedan cargados los pedidos realizados por otro usuario.

Ej: Me logueo con pepe5@gmail.com y cargo unos pedidos al carrito luego salgo e ingreso con pepe7@gmail.com y los pedidos cargados al carrito por pepe5 aparecen cargados en el carrito de pepe7 al momento de loguearse.

## Captura
user pepe5, de aqui cargo los pedidos en pantalla
![image](https://github.com/ochay33/proyecto-Bar-Nadir/assets/53904695/f424824e-2701-439a-ae7f-a64f9f27cb1a)
user pepe7, los pedidos cargados por pepe5 aparecen en el carrito de pepe7
![image](https://github.com/ochay33/proyecto-Bar-Nadir/assets/53904695/37cdf5ce-3a2c-44e6-adac-7ef126fe4ad1)
PD: Arreglar "total"

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by ochay33** [comment]
Problema del carrito y del Total resuelto.
